group= ['local']
name= localhost ansible_host
value= 127.0.0.1 ansible_connection=local
host= ['localhost', 'ansible_host=127.0.0.1 ansible_connection=local']
hostname= localhost
hostvars[0]= ansible_host=127.0.0.1 ansible_connection=local
hostvars= [('ansible_host', '127.0.0.1'), ('ansible_connection', 'local')]
group= ['node_offline']
name= proxmox01
value= None
host= ['proxmox01']
hostname= proxmox01
hostvars[0]= 
hostvars= []
name= esx02-idrac
value= None
host= ['esx02-idrac']
hostname= esx02-idrac
hostvars[0]= 
hostvars= []
name= node01-idrac
value= None
host= ['node01-idrac']
hostname= node01-idrac
hostvars[0]= 
hostvars= []
name= vesxi01
value= None
host= ['vesxi01']
hostname= vesxi01
hostvars[0]= 
hostvars= []
name= vesxi02
value= None
host= ['vesxi02']
hostname= vesxi02
hostvars[0]= 
hostvars= []
name= kube01
value= None
host= ['kube01']
hostname= kube01
hostvars[0]= 
hostvars= []
name= powerconnect01
value= None
host= ['powerconnect01']
hostname= powerconnect01
hostvars[0]= 
hostvars= []
group= ['control_node']
name= control01
value= None
host= ['control01']
hostname= control01
hostvars[0]= 
hostvars= []
name= vcontrol01
value= None
host= ['vcontrol01']
hostname= vcontrol01
hostvars[0]= 
hostvars= []
group= ['tower_control_node', 'children']
group= ['tower_control_node']
name= localhost
value= None
host= ['localhost']
hostname= localhost
hostvars[0]= 
hostvars= []
group= ['vsphere_control_node', 'children']
group= ['vmware_control_node', 'children']
group= ['ca_keyring', 'children']
group= ['jenkins_master', 'children']
group= ['cicd_node', 'children']
group= ['cicd_node']
name= admin[01
value= 03]
host= ['admin[01=03]']
hostname= admin[01:03]
hostvars[0]= 
hostvars= []
group= ['chef_inspec', 'children']
group= ['jenkins_agent', 'children']
group= ['cert_node', 'children']
group= ['stepca_certs', 'children']
group= ['machine_baremetal']
group= ['machine_vm', 'children']
group= ['ca_domain', 'children']
group= ['ca_domain_int_johnson', 'children']
group= ['os_windows']
group= ['os_windows', 'children']
group= ['windows', 'children']
group= ['ca_domain_int_johnson']
name= control01
value= None
host= ['control01']
hostname= control01
hostvars[0]= 
hostvars= []
name= vcontrol01
value= None
host= ['vcontrol01']
hostname= vcontrol01
hostvars[0]= 
hostvars= []
name= media01
value= None
host= ['media01']
hostname= media01
hostvars[0]= 
hostvars= []
group= ['ca_domain_int_dettonville']
name= vcontrol01
value= None
host= ['vcontrol01']
hostname= vcontrol01
hostvars[0]= 
hostvars= []
group= ['ca_domain_int_dettonville', 'children']
group= ['dhcp_hosts', 'children']
group= ['linux_ip_dhcp', 'children']
group= ['baremetal_dhcp']
group= ['vmware_vm_dhcp', 'children']
group= ['vmware_new_vm_linux']
group= ['vmware_new_vm_windows']
group= ['linux_ip_static', 'children']
group= ['linux_ip_static']
name= control01
value= None
host= ['control01']
hostname= control01
hostvars[0]= 
hostvars= []
name= media01
value= None
host= ['media01']
hostname= media01
hostvars[0]= 
hostvars= []
group= ['vmware_linux_ip_static', 'children']
group= ['vmware_linux_ip_dhcp', 'children']
group= ['vmware_int_johnson', 'children']
group= ['vmware_int_dettonville', 'children']
group= ['nameserver', 'children']
group= ['ns_master', 'children']
group= ['ns_slave', 'children']
group= ['kvm_host']
group= ['bind_master', 'children']
group= ['dhcp_master']
group= ['bind_slave']
group= ['dhcp_slave']
group= ['mergerfs']
group= ['linux', 'children']
group= ['vmware_image_redhat_7']
group= ['vmware_image_redhat_8']
group= ['vmware_image_debian_9']
group= ['vmware_image_debian_10']
group= ['vmware_image_debian_11']
group= ['vmware_image_ubuntu_18']
group= ['vmware_image_ubuntu_20']
name= vcontrol01
value= None
host= ['vcontrol01']
hostname= vcontrol01
hostvars[0]= 
hostvars= []
group= ['vmware_image_ubuntu_22']
name= admin[01
value= 03]
host= ['admin[01=03]']
hostname= admin[01:03]
hostvars[0]= 
hostvars= []
name= vmu22-[01
value= 03]
host= ['vmu22-[01=03]']
hostname= vmu22-[01:03]
hostvars[0]= 
hostvars= []
group= ['vmware_image_centos_7']
group= ['vmware_image_centos_8']
name= vmc08-[01
value= 03]
host= ['vmc08-[01=03]']
hostname= vmc08-[01:03]
hostvars[0]= 
hostvars= []
group= ['vmware_image_windows_2012']
name= win2012-01
value= None
host= ['win2012-01']
hostname= win2012-01
hostvars[0]= 
hostvars= []
group= ['vmware_image_windows_2016']
group= ['vmware_image_windows_2019']
name= win2019-01
value= None
host= ['win2019-01']
hostname= win2019-01
hostvars[0]= 
hostvars= []
group= ['docker_ci']
group= ['vm_template']
group= ['vmware_vm', 'children']
group= ['vmware_appliance']
group= ['vmware_vm_linux']
group= ['vmware_vm_linux', 'children']
group= ['vmware_vm_windows']
group= ['vmware_vm_windows', 'children']
group= ['molecule_docker_linux']
group= ['os_vcenter', 'children']
group= ['os_esxi', 'children']
group= ['os_linux', 'children']
group= ['os_linux', 'vars']
group= ['os_centos', 'children']
group= ['os_centos', 'vars']
group= ['os_centos_7']
group= ['os_centos_8']
group= ['os_redhat']
group= ['os_redhat', 'children']
group= ['os_redhat', 'vars']
group= ['os_redhat_7']
group= ['os_redhat_8']
group= ['os_debian', 'children']
group= ['os_debian', 'vars']
group= ['os_debian_9']
group= ['os_debian_10']
group= ['os_debian_11']
group= ['os_ubuntu', 'children']
group= ['os_ubuntu', 'vars']
group= ['os_ubuntu_18']
group= ['os_ubuntu_20']
group= ['os_ubuntu_22']
group= ['step_ca_cli', 'children']
group= ['machine_baremetal', 'children']
group= ['baremetal', 'children']
group= ['baremetal_linux']
name= control01
value= None
host= ['control01']
hostname= control01
hostvars[0]= 
hostvars= []
name= media01
value= None
host= ['media01']
hostname= media01
hostvars[0]= 
hostvars= []
group= ['veeam_agent', 'children']
group= ['proxmox']
name= proxmox01
value= None
host= ['proxmox01']
hostname= proxmox01
hostvars[0]= 
hostvars= []
group= ['vmware_guest_auto']
group= ['vmware_vsphere', 'children']
group= ['vmware_esx_host', 'children']
group= ['vmware_physical_esx_host']
name= esx00
value= None
host= ['esx00']
hostname= esx00
hostvars[0]= 
hostvars= []
name= esx01
value= None
host= ['esx01']
hostname= esx01
hostvars[0]= 
hostvars= []
name= esx02
value= None
host= ['esx02']
hostname= esx02
hostvars[0]= 
hostvars= []
name= esx10
value= None
host= ['esx10']
hostname= esx10
hostvars[0]= 
hostvars= []
group= ['vmware_vcenter']
name= vcenter7
value= None
host= ['vcenter7']
hostname= vcenter7
hostvars[0]= 
hostvars= []
group= ['vmware_nested_esx']
group= ['vmware_windows_ip_dhcp']
name= win2012-01
value= None
host= ['win2012-01']
hostname= win2012-01
hostvars[0]= 
hostvars= []
name= win2019-01
value= None
host= ['win2019-01']
hostname= win2019-01
hostvars[0]= 
hostvars= []
group= ['vmware_flavor_small']
name= vmu22-[01
value= 03]
host= ['vmu22-[01=03]']
hostname= vmu22-[01:03]
hostvars[0]= 
hostvars= []
name= vmc08-[02
value= 03]
host= ['vmc08-[02=03]']
hostname= vmc08-[02:03]
hostvars[0]= 
hostvars= []
name= win2012-01
value= None
host= ['win2012-01']
hostname= win2012-01
hostvars[0]= 
hostvars= []
name= win2019-01
value= None
host= ['win2019-01']
hostname= win2019-01
hostvars[0]= 
hostvars= []
group= ['vmware_flavor_medium']
name= admin[01
value= 03]
host= ['admin[01=03]']
hostname= admin[01:03]
hostvars[0]= 
hostvars= []
name= vmc08-01
value= None
host= ['vmc08-01']
hostname= vmc08-01
hostvars[0]= 
hostvars= []
group= ['vmware_flavor_large']
group= ['vmware_linux_ip_static']
name= vcontrol01
value= None
host= ['vcontrol01']
hostname= vcontrol01
hostvars[0]= 
hostvars= []
group= ['vmware_linux_ip_static_int_johnson']
group= ['vmware_linux_ip_dhcp_int_johnson']
name= admin[01
value= 03]
host= ['admin[01=03]']
hostname= admin[01:03]
hostvars[0]= 
hostvars= []
name= vmc08-[01
value= 03]
host= ['vmc08-[01=03]']
hostname= vmc08-[01:03]
hostvars[0]= 
hostvars= []
name= vmu22-[01
value= 03]
host= ['vmu22-[01=03]']
hostname= vmu22-[01:03]
hostvars[0]= 
hostvars= []
group= ['vmware_linux_ip_dhcp_int_dettonville']
group= ['esxi', 'children']
group= ['docker', 'children']
group= ['docker']
group= ['docker_registry']
name= media01
value= None
host= ['media01']
hostname= media01
hostvars[0]= 
hostvars= []
group= ['kickstart']
name= admin01
value= None
host= ['admin01']
hostname= admin01
hostvars[0]= 
hostvars= []
group= ['dhcp_client_mac_interface', 'children']
group= ['network_switch']
name= powerconnect01
value= None
host= ['powerconnect01']
hostname= powerconnect01
hostvars[0]= 
hostvars= []
group= ['fog_server']
group= ['ldap_client', 'children']
group= ['nfs_service', 'children']
group= ['ntp_client', 'children']
group= ['ntp_server']
name= vmc08-01
value= None
host= ['vmc08-01']
hostname= vmc08-01
hostvars[0]= 
hostvars= []
group= ['samba_client']
group= ['backup_server', 'children']
group= ['postfix_server', 'children']
group= ['postfix_server']
name= control01
value= None
host= ['control01']
hostname= control01
hostvars[0]= 
hostvars= []
name= media01
value= None
host= ['media01']
hostname= media01
hostvars[0]= 
hostvars= []
group= ['postfix_client', 'children']
group= ['iscsi_client', 'children']
group= ['docker_image_builder', 'children']
group= ['docker_stack', 'children']
group= ['docker_control_node', 'children']
group= ['docker_admin_node']
name= admin[01
value= 03]
host= ['admin[01=03]']
hostname= admin[01:03]
hostvars[0]= 
hostvars= []
group= ['docker_samba_node']
group= ['docker_media_node']
name= media01
value= None
host= ['media01']
hostname= media01
hostvars[0]= 
hostvars= []
group= ['docker_awx_node', 'children']
group= ['docker_ml_node']
group= ['docker_cobbler_node']
group= ['openstack_kolla_node']
name= admin[01
value= 03]
host= ['admin[01=03]']
hostname= admin[01:03]
hostvars[0]= 
hostvars= []
group= ['nginx_service']
group= ['ansible_controller', 'children']
group= ['cobbler_native']
group= ['solrcloud']
group= ['zookeeper']
group= ['cobbler_container']
group= ['k8s_cluster', 'children']
group= ['kube_master']
name= kube01
value= None
host= ['kube01']
hostname= kube01
hostvars[0]= 
hostvars= []
group= ['kube_node']
group= ['etcd']
name= kube01
value= None
host= ['kube01']
hostname= kube01
hostvars[0]= 
hostvars= []
group= ['cloudstack_cluster', 'children']
group= ['cloudstack_master']
group= ['cloudstack_compute']
group= ['openstack', 'children']
group= ['openstack_control']
group= ['openstack_network']
group= ['openstack_compute']
group= ['openstack_storage']
group= ['openstack_monitoring']
group= ['openstack_deployment']
group= ['dell_idrac_hosts']
name= esx02-idrac
value= None
host= ['esx02-idrac']
hostname= esx02-idrac
hostvars[0]= 
hostvars= []
name= node01-idrac
value= None
host= ['node01-idrac']
hostname= node01-idrac
hostvars[0]= 
hostvars= []
group= ['idrac_syslog']
group= ['idrac_syslog', 'vars']
group= ['baremetal_windows']
name= ljlaptop
value= None
host= ['ljlaptop']
hostname= ljlaptop
hostvars[0]= 
hostvars= []
group= ['windows']
name= win2012-01 become_method
value= runas
host= ['win2012-01', 'become_method=runas']
hostname= win2012-01
hostvars[0]= become_method=runas
hostvars= [('become_method', 'runas')]
name= ljlaptop
value= None
host= ['ljlaptop']
hostname= ljlaptop
hostvars[0]= 
hostvars= []
group= ['windows', 'vars']
group= ['connectivity_tests', 'children']
all:
  children:
    ansible_controller:
      children:
        control_node: {}
    backup_server:
      children:
        control_node: {}
    baremetal:
      children:
        machine_baremetal: {}
    baremetal_linux:
      hosts:
        control01: {}
        media01: {}
    baremetal_windows:
      hosts:
        ljlaptop: {}
    ca_domain:
      children:
        ca_domain_int_dettonville: {}
        ca_domain_int_johnson: {}
    ca_domain_int_dettonville:
      children:
        vmware_linux_ip_dhcp_int_dettonville: {}
        vmware_physical_esx_host: {}
        vmware_vsphere: {}
      hosts:
        vcontrol01: {}
    ca_domain_int_johnson:
      children:
        baremetal_linux: {}
        baremetal_windows: {}
        vmware_linux_ip_dhcp_int_johnson: {}
        vmware_linux_ip_static_int_johnson: {}
      hosts:
        control01: {}
        media01: {}
        vcontrol01: {}
    ca_keyring:
      children:
        control_node: {}
    cert_node:
      children:
        ca_domain: {}
    chef_inspec:
      children:
        cicd_node: {}
    cicd_node:
      children:
        control_node: {}
      hosts:
        admin[01:03]: {}
    cloudstack_cluster:
      children:
        cloudstack_compute: {}
        cloudstack_master: {}
    connectivity_tests:
      children:
        linux: {}
        windows: {}
    control_node:
      hosts:
        control01: {}
        vcontrol01: {}
    dell_idrac_hosts:
      hosts:
        esx02-idrac: {}
        node01-idrac: {}
    dhcp_client_mac_interface:
      children:
        network_switch: {}
        vmware_vm_dhcp: {}
    dhcp_hosts:
      children:
        vmware_linux_ip_dhcp: {}
    docker:
      children:
        docker_stack: {}
        vmware_vm: {}
    docker_admin_node:
      hosts:
        admin[01:03]: {}
    docker_awx_node:
      children:
        control_node: {}
    docker_control_node:
      children:
        control_node: {}
    docker_image_builder:
      children:
        control_node: {}
    docker_media_node:
      hosts:
        media01: {}
    docker_registry:
      hosts:
        media01: {}
    docker_stack:
      children:
        docker_admin_node: {}
        docker_control_node: {}
        docker_media_node: {}
        docker_ml_node: {}
    esxi:
      children:
        vmware_vm: {}
    etcd:
      hosts:
        kube01: {}
    iscsi_client:
      children:
        control_node: {}
    jenkins_agent:
      children:
        cicd_node: {}
    jenkins_master:
      children:
        control_node: {}
    k8s_cluster:
      children:
        kube_master: {}
        kube_node: {}
    kickstart:
      hosts:
        admin01: {}
    kube_master:
      hosts:
        kube01: {}
    ldap_client:
      children:
        os_linux: {}
    linux:
      children:
        baremetal_linux: {}
        molecule_docker_linux: {}
        vmware_vm_linux: {}
    linux_ip_dhcp:
      children:
        baremetal_dhcp: {}
        vmware_vm_dhcp: {}
    linux_ip_static:
      children:
        vmware_linux_ip_static: {}
      hosts:
        control01: {}
        media01: {}
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_host: 127.0.0.1
    machine_baremetal:
      children:
        baremetal_linux: {}
        baremetal_windows: {}
        vmware_physical_esx_host: {}
    machine_vm:
      children:
        vmware_nested_esx: {}
        vmware_vm: {}
    nameserver:
      children:
        ns_master: {}
        ns_slave: {}
    network_switch:
      hosts:
        powerconnect01: {}
    nfs_service:
      children:
        os_linux: {}
    node_offline:
      hosts:
        esx02-idrac: {}
        kube01: {}
        node01-idrac: {}
        powerconnect01: {}
        proxmox01: {}
        vesxi01: {}
        vesxi02: {}
    ns_master:
      children:
        bind_master: {}
        dhcp_master: {}
    ns_slave:
      children:
        bind_slave: {}
        dhcp_slave: {}
    ntp_client:
      children:
        os_linux: {}
    ntp_server:
      hosts:
        vmc08-01: {}
    openstack:
      children:
        openstack_compute: {}
        openstack_control: {}
        openstack_deployment: {}
        openstack_monitoring: {}
        openstack_network: {}
        openstack_storage: {}
    openstack_kolla_node:
      hosts:
        admin[01:03]: {}
    os_centos:
      children:
        os_centos_7: {}
        os_centos_8: {}
      vars:
        ansible_group_priority: 0
    os_debian:
      children:
        os_debian_10: {}
        os_debian_11: {}
        os_debian_9: {}
      vars:
        ansible_group_priority: 0
    os_esxi:
      children:
        vmware_esx_host: {}
    os_linux:
      children:
        linux: {}
        os_centos: {}
        os_debian: {}
        os_redhat: {}
        os_ubuntu: {}
      vars:
        ansible_group_priority: -1
    os_redhat:
      children:
        os_redhat_7: {}
        os_redhat_8: {}
      vars:
        ansible_group_priority: 0
    os_ubuntu:
      children:
        os_ubuntu_18: {}
        os_ubuntu_20: {}
        os_ubuntu_22: {}
      vars:
        ansible_group_priority: 0
    os_vcenter:
      children:
        vmware_vcenter: {}
    os_windows:
      children:
        windows: {}
    postfix_client:
      children:
        os_linux: {}
    postfix_server:
      children:
        control_node: {}
      hosts:
        control01: {}
        media01: {}
    proxmox:
      hosts:
        proxmox01: {}
    step_ca_cli:
      children:
        os_linux: {}
    stepca_certs:
      children:
        machine_vm: {}
    tower_control_node:
      hosts:
        localhost: {}
    veeam_agent:
      children:
        machine_baremetal: {}
    vmware_control_node:
      children:
        control_node: {}
    vmware_esx_host:
      children:
        vmware_physical_esx_host: {}
    vmware_flavor_medium:
      hosts:
        admin[01:03]: {}
        vmc08-01: {}
    vmware_flavor_small:
      hosts:
        vmc08-[02:03]: {}
        vmu22-[01:03]: {}
        win2012-01: {}
        win2019-01: {}
    vmware_image_centos_8:
      hosts:
        vmc08-[01:03]: {}
    vmware_image_ubuntu_20:
      hosts:
        vcontrol01: {}
    vmware_image_ubuntu_22:
      hosts:
        admin[01:03]: {}
        vmu22-[01:03]: {}
    vmware_image_windows_2012:
      hosts:
        win2012-01: {}
    vmware_image_windows_2019:
      hosts:
        win2019-01: {}
    vmware_int_dettonville:
      children:
        vmware_linux_ip_dhcp_int_dettonville: {}
    vmware_int_johnson:
      children:
        vmware_linux_ip_dhcp_int_johnson: {}
        vmware_linux_ip_static_int_johnson: {}
    vmware_linux_ip_dhcp:
      children:
        vmware_linux_ip_dhcp_int_dettonville: {}
        vmware_linux_ip_dhcp_int_johnson: {}
    vmware_linux_ip_dhcp_int_johnson:
      hosts:
        admin[01:03]: {}
        vmc08-[01:03]: {}
        vmu22-[01:03]: {}
    vmware_linux_ip_static:
      children:
        vmware_linux_ip_static_int_johnson: {}
      hosts:
        vcontrol01: {}
    vmware_physical_esx_host:
      hosts:
        esx00: {}
        esx01: {}
        esx02: {}
        esx10: {}
    vmware_vcenter:
      hosts:
        vcenter7: {}
    vmware_vm:
      children:
        vmware_appliance: {}
        vmware_flavor_large: {}
        vmware_flavor_medium: {}
        vmware_flavor_small: {}
        vmware_vm_linux: {}
        vmware_vm_windows: {}
    vmware_vm_dhcp:
      children:
        vmware_linux_ip_dhcp: {}
    vmware_vm_linux:
      children:
        vmware_image_centos_7: {}
        vmware_image_centos_8: {}
        vmware_image_debian_10: {}
        vmware_image_debian_11: {}
        vmware_image_debian_9: {}
        vmware_image_redhat_7: {}
        vmware_image_redhat_8: {}
        vmware_image_ubuntu_18: {}
        vmware_image_ubuntu_20: {}
        vmware_image_ubuntu_22: {}
    vmware_vm_windows:
      children:
        vmware_image_windows_2012: {}
        vmware_image_windows_2016: {}
        vmware_image_windows_2019: {}
    vmware_vsphere:
      children:
        vmware_esx_host: {}
        vmware_nested_esx: {}
        vmware_vcenter: {}
    vmware_windows_ip_dhcp:
      hosts:
        win2012-01: {}
        win2019-01: {}
    vsphere_control_node:
      children:
        control_node: {}
    windows:
      children:
        baremetal_windows: {}
        vmware_vm_windows: {}
      hosts:
        ljlaptop: {}
        win2012-01:
          become_method: runas
      vars:
        ansible_connection: winrm
        ansible_port: 5986
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_transport: ntlm
        become_method: runas

